### ISSUE TITLE
Email Template / Shorthand meta format-detection rules

### ISSUE THREAD

**Issue by TedGoas** [M-J-Robbins/good-email-code#1]
On the page for [email template](https://www.goodemailcode.com/email-code/template.html), would it make sense to shorthand for `format-detection`?

Eg: `<meta name="format-detection" content="telephone=no, date=no, address=no, email=no">`

Each property name is descriptive and the meta tag for `viewport` follows this pattern.

Would using shorthand here make the code _more_ or _less_ legible? What's your take?

**Comment by M-J-Robbins** [comment]
Oh nice, didn't know that was possible to combine them.  I'll do some more research and update 👍

**Comment by hteumeuleu** [comment]
Came here to post exactly the same thing! I had to use this this morning and the shorthand seems to work similarly (at least in Apple Mail and Spark Mail). More tests would be good for this to know if there any drawback to using the shorthand.

**Comment by M-J-Robbins** [comment]
Just pushed an update, thanks a lot both of you for point this one out 👍
