### ISSUE TITLE
Remove <o:AllowPNG/> ?

### ISSUE THREAD

**Issue by hteumeuleu** [M-J-Robbins/good-email-code#10]
In your [Email Template](https://www.goodemailcode.com/email-code/template) code, I notice you have the `<o:AllowPNG/>` declaration. Have you ever noticed it making any difference at rendering?

I tried to research it a few years ago. And Microsoft's official documentation says:

>  Specifies whether PNG (Portable Network Graphics) is used as an image format on a Web page.
> If `<o:AllowPNG/>` is specified, PNG format is used.
> As opposed to any other file format, images saved in PNG might improve in quality and their file size might reduce (decreasing download time) when targeted browsers support the PNG format.

My understanding is that this makes a difference when saving a Word document as HTML. But not for rendering HTML in Word/Outlook. I've removed this from all my templates a few years ago, I use PNG all the times, and never had a problem with it.

**See also:**

* https://stigmortenmyre.no/mso/html/shared/ofeleallowpng.htm
* https://www.stigviewer.com/stig/microsoft_office_system_2013/2017-01-04/finding/V-17561

**Comment by M-J-Robbins** [comment]
Nice, good catch.  
I've removed it 👍
