### ISSUE TITLE
A couple of typos

### ISSUE THREAD

**Issue by leac** [M-J-Robbins/good-email-code#12]
I'm enjoying your site very much and just politely letting you know of a couple of typos on the [Email Templates](https://www.goodemailcode.com/email-code/template) page:

- "if the file**s** is save**s**" - should be "if the file is saved"
- "was rename**s** to" - should be "was renamed to"
- "stand alon**g** content" - should be " stand alone content", or, better yet, "stand-alone content"

**Comment by M-J-Robbins** [comment]
Hi @leac 
Thanks so much for the feedback, I've just pushed a commit so those _should_ all be fixed now. 
Sorry for the delay, I missed the notification.
