### ISSUE TITLE
Container > Wrong order of tags

### ISSUE THREAD

**Issue by bil0u** [M-J-Robbins/good-email-code#17]
Hi !

I found a small issue in the [examples for containers](https://www.goodemailcode.com/email-code/container), section "Adding a background colour to the outer body"

```html
<div style="background:#000000">
  <!--[if true]>
  <table role="presentation" width="100%" align="center" style="background:#000000"><tr><td></td><td style="width:37.5em;background:#ffffff">
  <![endif]-->
  <div style="max-width:37.5em; margin:0 auto;background:#ffffff">
    <!-- email content in here -->
  </div>
  <!--[if true]>
  </td></tr><td></td></table>       <-- Here
  <![endif]-->
</div>
```

The table row closing tag is misplaced.

`</td></tr><td></td></table>` should be `</td><td></td></tr></table>`

**Comment by M-J-Robbins** [comment]
Sorry I must have missed this issue, just pushed a fix.
Thanks for finding it 😁
