### ISSUE TITLE
LInk Buttons - Outlook for Mac

### ISSUE THREAD

**Issue by M-J-Robbins** [M-J-Robbins/good-email-code#18]
Hi Mark, 

i have a little Problem. I tried your code for LInk Buttons  and everything works fine on Outlook for Windows. 
But as soon as the recipient got outlook for Mac, it gets bad. 

Here two screenshots how it should look and how it looks on Mac. Do you have a suggestion for something like that? 
![image](https://user-images.githubusercontent.com/89200332/168066146-342bad20-63cf-43f2-a4bb-1c3543f74bd5.png)

and mac is rendering it like this:
![image](https://user-images.githubusercontent.com/89200332/168066254-a0cdecb7-db6f-4378-8969-8d11e6d93d17.png)

If you can notice also the double underlining although i disabled decoration for links. 

Can you help me in any way? 

Best regards,
Majed

_Originally posted by @Majed610 in https://github.com/M-J-Robbins/good-email-code/issues/8#issuecomment-1124886152_

**Comment by M-J-Robbins** [comment]
Hi @Majed610, 
It should work well as [CSS support is very good in outlook mac](https://www.caniemail.com/clients/outlook/#macos), however there are a few potential things that could be causing the issue you're seeing

* Conflicting CSS elsewhere in the template 
  * Try sending it without anything else in the template. If it works then slowly add other bits in until it breaks and that will highlight the issue.
  * If the simple code doesn't work then there may be a typo, or there may be an issue with a particular version of Outlook, if so could you share the code as you have it and the Outlook version number, I can try and take a look at it.
* It could be the ESP changing something in your code.
  * Send a test and export the raw code, then compare this to the original code you sent, if there is anything added, removed or edited, file a bug report for the ESP also, let me know and I can see if there is another option.
* The code could also be getting altered by a mail server.  In the past I've seen cases of MS Exchange removing bits of code and causing issues.
  * This is a hard one to work around if the rules are very strict, if you can export the processed code and share that along with the original I can take a look and maybe suggest some work arounds

**Comment by Majed610** [comment]
Hi Mark, 

thanks a lot for the suggestions. 

I am going to analyse the received Email Code to check if the MS Exchange is changing anything.
