### ISSUE TITLE
minor grammatical error on the newly created Text page

### ISSUE THREAD

**Issue by SprayCanMan** [M-J-Robbins/good-email-code#2]
Just above the section titled "Offset" there is a minor typo.  I figured this would be the best place to point it out, let me know if there is a better spot for that.

Typo:
"Be carful when underlining text as this is often a visual queue for a hyperlink and _**may lead confuse the reader**_."

Page:
https://www.goodemailcode.com/email-code/text

**Comment by M-J-Robbins** [comment]
Great catch thanks, should be updated now.
