### ISSUE TITLE
`xmlns` attributes for `html` tag

### ISSUE THREAD

**Issue by o-t-w** [M-J-Robbins/good-email-code#21]
Great resource. 
I couldn't see any explanation for these attributes for the html tag: `xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"`. Why is it a good practice to include them?

**Comment by cossssmin** [comment]
You need them for VML code to work (i.e. when doing background images for Outlook). This is the short version, I'm sure Mark can explain in much greater detail :)

**Comment by M-J-Robbins** [comment]
Hiya sorry for delayed response. I was away for a while then started a new job so missed this.

So yes as Cosmin said these are to make VML render. You can also put it directly on a VML shape [like I do here}(https://www.goodemailcode.com/email-enhancements/svg-to-vml#xmlns). I need to do some more research on the `xmlns:o="urn:schemas-microsoft-com:office:office"` 

I've just pushed an update

**Comment by M-J-Robbins** [comment]
updated template page
https://www.goodemailcode.com/email-code/template#xmlns
