### ISSUE TITLE
MSO- Styles in Email???

### ISSUE THREAD

**Issue by WPP-Fonts** [M-J-Robbins/good-email-code#24]
In https://www.goodemailcode.com/email-enhancements/mso-styles.html#:~:text=mso%2Dline%2Dheight%2Drule,least%20as%20the%20default%20value.

All your examples are using inline CSS. I tried defining the styles in a CSS block in the `<head>`. But that does now seem to work.

Could you please confirm one way or another?

Thank you.

**Comment by M-J-Robbins** [comment]
Yeah these should work when set as style in the head too. 
I use inline examples as they are quick to copy and paste so people can see them work in Outlook. 

i should add a note to the page when i get a moment.

I'm closing this for now but feel free to reopen if you need more info
