### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by diana1357** [M-J-Robbins/good-email-code#4]
Hi!

There is a small typo in the footer link that lead me to this page:

"If you find something that isn't working, please sumit issues via github" 

 I guess it should be "submit":

"If you find something that isn't working, please submit issues via github. "

(It just stands out on the page).

Thanks for building the site I have already found many invaluable tips!

**Comment by M-J-Robbins** [comment]
Ah amazing thanks.  Should be fixed now.
Quite ironic placement for a typo :)
