### ISSUE TITLE
`<hr>` alignment

### ISSUE THREAD

**Issue by cossssmin** [M-J-Robbins/good-email-code#5]
`<hr>`s are left-aligned by default ([source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr#attr-align)). 

In the [Align section](https://www.goodemailcode.com/email-code/hr#align), you mention they're centered by default. I just checked and it seems only Outlook (Windows) centers `<hr>` by default, the rest align it to the left as in the spec.

Also, small typo:

> Because we’ve removed the _boarder_

**Comment by M-J-Robbins** [comment]
I've got to fix my notifications for github, I keep missing these issues.

I've tested again and `<hr style="width:50px">` seems to always appear in the centre.  Not seen it left aligned anywhere.

Will fix that typo now 👍
