### ISSUE TITLE
Feature: Email build task webpack

### ISSUE THREAD

**Issue by macmladen** [M-J-Robbins/good-email-code#6]
This is not a bug _per se_ but more like a feature request:

I would like you to include some webpack (or gulp) task which takes regular HTML/CSS/Sass and builds into e-mail friendly form which is suitable for most clients (like Gmail web/desktop, Android and iOS)

**Comment by M-J-Robbins** [comment]
Unfortunately due to conflicts with my day job I'm unable to work on anything like that (also it's beyond my skillset).  But would be a very cool thing!

**Comment by cossssmin** [comment]
@macmladen have you tried Maizzle? 

https://github.com/maizzle/maizzle

**Comment by macmladen** [comment]
I haven't. But **Tailwind** hits on my nerve where you have more classes than content, let alone needed tags.

However, @cossssmin I must agree that I should first check to see how optimized the final code is before making a statement.

What is your opinion, are you using it?

**Comment by cossssmin** [comment]
> What is your opinion, are you using it?

Yup, use them both and love them, though I might be biased 😁
