### ISSUE TITLE
Email report template (with static image chart)

### ISSUE THREAD

**Issue by FGRibreau** [M-J-Robbins/good-email-code#9]
Hello @M-J-Robbins !

Would you be interested by a PR that adds an email report template that embeds [static image-charts](https://www.image-charts.com)?

**Comment by M-J-Robbins** [comment]
Generally I'm trying to keep things very minimal and focused on basic code to begin with but always open to ideas. what do you see being in the charts?

**Comment by Theofvr** [comment]
I'm interested as well, we send customized email reports to our customer and we already use Image charts (free plan) but I wonder if there are best practices.

**Comment by M-J-Robbins** [comment]
Oh right I get it.  
This website is just for focusing on email code, so from the point of view of this website it's just inserting an image (which I'm going to write up), obviously with a product like this there is a lot more that goes into it but I'm not covering third party products here.

**Comment by FGRibreau** [comment]
No problem, thanks for your quick answer :)
